query Footer {
  metadadoBy(slug: "rodape") {
    camposRodape {
      funcionamento {
        horarioDeAbertura
        horarioDeEncerramento
      }
      endereco {
        cidade
        estado
        numero
        pais
        rua
      }
      contato {
        eMail
        telefone
      }
    }
  }
}